fe = 100;
Te = 1/fe;
t = 0:Te:12;
s = [zeros(1,4*fe+1) 10*ones(1,2*fe) zeros(1,3*fe) 15*ones(1,2*fe) zeros(1,fe)];
b = randn(size(t));
mean(b);
std(b);
b = b-mean(b);
mean(b);
b = b/std(b);
std(b);
b = b*2*std(b);
figure(4);
hist(b);
sb = b + s;
figure(1);
plot(t,s);
grid;
figure(2);
plot(t,s,t,b);
figure(3);
plot(t,sb);
